### ISSUE TITLE
Problems with stats API

### ISSUE THREAD

**Issue by kmz27** [vx3r/wg-gen-web#107]
I have an issue where when I hit the status page it doesn't load the client information and puts some errors in my logs.

Public Key, Number of clients etc does load.
![unknown](https://user-images.githubusercontent.com/44536631/178222719-e12b6870-b689-47ee-a357-b6e4168b42fb.png)

**Comment by motsu35** [comment]
Hey, I don't have a fix for the error, but I know the cause and how to get it to go away (if you havent already figured it out @kmz27 )

this happens when you don't have any peers that have connected to your wg server.  To get this fixed, start up your wg server... since the wg-gen-web project overrides your wg0.conf file, it helps to get your running wireguard in sync by starting your docker compose, ctrl+c'ing it, bringing your wg server down and back up (this guarentees that the wg config being used by wg is the one generated by wg-gen-wen), then starting your docker compose back up again.

create a host if you haven't already. This will create the deffinition in your wg0.conf file. There are instructions on how to auto reload the server on new clients, but for now, bring wg down and back up. you can now connect your client. at this point, you should be able to go to the api status page without getting the error.

**Comment by kmz27** [comment]
Hi, at some point I got it working with your instructions but it broke again and I cant get it to work atm.
I think we can close this one.
