### ISSUE TITLE
Authelia

### ISSUE THREAD

**Issue by moookino** [vx3r/wg-gen-web#20]
Hi @vx3r 

nice work and project. Want to try with help regrading authelia usage, it's currently playing nice with Traefik v2.0 and doesn't required any robust work to setup
You can use https://github.com/authelia/authelia/blob/master/docs/deployment/supported-proxies/traefik2.x.md for reference. I've successful setup on my server based on that documentation and the user management can be done by authelia config files.

Hope that helps

**Comment by vx3r** [comment]
Hi @moookino 

I have the same setup with Nginx.
The idea here is to make wg-gen-web avare of the user and group coming from Authelia and based on that make custom decisions. 
We need to decide what are the use cases: 

- simply display the user connected 
- define admin group who can modify server confs 
- user can create vpn clients for him self And can only see his clients

Or anything else.. 
i don’t really know if this is required because you can define group vpn in authelia and give access to users in this group without any modification.

I need some inputs

**Comment by moookino** [comment]
I'm not super familiar with, my thoughts on that if e.g. admin can use doman.com/admin endpoint and based on Authelia can access that endpoint, then it could be same for different users, when some user-oriented spaces, like domain.com/user/namespace, which is accessible by user and admin. This could be easily achievable with traefik and authelia setup

**Comment by vx3r** [comment]
As Oauth2 OIDC is implemented i'm closing the issue, its much easier than Authelia
